services:
  tranquil-pds:
    image: atcr.io/tranquil.farm/tranquil-pds:latest
    pull_policy: refresh
    pull_refresh_after: 48h
    restart: unless-stopped
    environment:
      PDS_HOSTNAME: pds.hackclub.community
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "3000"
      PDS_USER_HANDLE_DOMAINS: bsky.hackclub.community
      PDS_AGE_ASSURANCE_OVERRIDE: "true"
      INVITE_CODE_REQUIRED: "true"
      CONTACT_EMAIL: "society@alumni.hackclub.community"
      MAX_BLOB_SIZE: "2147483648" # 2 GB
      DATABASE_URL: "postgresql://pds-prod:4f03c7f15a4689edc0558714b50fbff61c7fb9fdbae3382377b138fbf8a49a818b5ae3bcd9612357524009da4645fc1e690829d1cd7920caef627f55fb4d7c8e8798b9@postgres:5432/pds"
    env_file: .env.production.decrypted
    ports:
      - 3000:3000
    volumes:
      - blob_data:/var/lib/tranquil-pds/blobs
      - store_data:/var/lib/tranquil-pds/store
    networks:
      - pds-ops
      - kamal-proxy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/xrpc/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: pds-prod
      POSTGRES_PASSWORD: "4f03c7f15a4689edc0558714b50fbff61c7fb9fdbae3382377b138fbf8a49a818b5ae3bcd9612357524009da4645fc1e690829d1cd7920caef627f55fb4d7c8e8798b9"
      POSTGRES_DB: pds
    volumes:
      # In memory of @mrrp.lol when Lewis had "/data" here and the account got nuked on restart including rotation key :(
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tranquil_pds -d pds"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - pds-ops

volumes:
  postgres_data:
  blob_data:
  store_data:

networks:
  pds-ops:
  kamal-proxy:
    external: true
    name: once