blank_issues_enabled: true
contact_links:
  - name: "#atproto-pds-dev on Hack Club Slack"
    url: https://hackclub.slack.com/archives/C09KQG6EALB
    about: For user support and dev chat in Hack Club Slack.